version: '3.9'

services:
  lanchonete-node:
    image: tech-challenge-lanchonete:latest
    container_name: lanchonete-node
    environment:
      - PORT=8080
    ports:
      - 8080:8080
    restart: unless-stopped