FROM node:lts-alpine

RUN adduser -D lanchonete-api

ARG PORT_SERVER=8080
ENV PORT $PORT_SERVER

EXPOSE $PORT

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY . .

RUN npm install -g nodemon && npm install

USER lanchonete-api

CMD ["npm", "run", "dev"]
