FROM node:lts-alpine

RUN adduser -D lanchonete-api

ARG PORT_SERVER=8080
ENV PORT $PORT_SERVER

EXPOSE $PORT

RUN mkdir -p /home/node/app && chown -R lanchonete-api /home/node/app

WORKDIR /home/node/app

COPY . .

RUN npm ci

USER lanchonete-api

RUN npm run build

CMD [ "node", "out/index.js" ]
