FROM node:lts-alpine

RUN adduser -D lanchonete-api

ARG PORT_SERVER=8080
ENV PORT $PORT_SERVER

EXPOSE $PORT

RUN mkdir -p /home/node/app

RUN chown -R lanchonete-api /home/node/app

WORKDIR /home/node/app

COPY package*.json ./

RUN npm ci

COPY --chown=lanchonete-api . .

USER lanchonete-api

RUN npm run build

CMD [ "node", "build/index.js" ]
