paths:
  /orders:
    get:
      summary: Lista todos os pedidos
      tags:
        - Pedidos
      responses:
        "200":
          description: Lista de pedidos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/OrderWithItems"
        "500":
          description: Erro interno do servidor
    post:
      summary: Cria um novo pedido
      tags:
        - Pedidos
      requestBody:
        description: Payload para criação de pedido
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                customerId:
                  required: true
                  type: integer
              example:
                customerId: 1
      responses:
        "201":
          description: Pedido criado com sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        "400":
          description: Invalid input
        "500":
          description: Server error
  /orders/{id}:
    get:
      summary: Exibe um pedido pelo ID
      parameters:
        - in: path
          name: id
          required: true
          description: ID do pedido
          schema:
            type: integer
      tags:
        - Pedidos
      responses:
        "200":
          description: Lista o pedido desejado filtrando pelo ID
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderWithItems"
        "500":
          description: Erro interno do servidor
  /orders/{id}/items:
    post:
      summary: Cria um novo item no pedido
      tags:
        - Pedidos
      parameters:
        - in: path
          name: id
          required: true
          description: ID do pedido
          schema:
            type: integer
      requestBody:
        description: Payload para criar um item no pedido
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productId:
                  type: integer
                  description: ID do Produto
                  example: 1
                quantity:
                  type: integer
                  description: Quantidade do Produto
                  example: 2
              required:
                - productId
                - quantity
      responses:
        "201":
          description: Exibe o pedido com o item criado
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  code:
                    type: string
                  status:
                    type: string
                  items:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                      category:
                        type: string
                      price:
                        type: number
                        format: float
                      description:
                        type: string
        "500":
          description: Erro interno do servidor
  /orders/{id}/items/{itemId}:
    put:
      summary: Atualiza um item existente do pedido
      tags:
        - Pedidos
      parameters:
        - in: path
          name: id
          required: true
          description: ID do pedido
          schema:
            type: integer
        - in: path
          name: itemId
          required: true
          description: ID do item no pedido
          schema:
            type: integer
      requestBody:
        description: Payload para atualizar um item no pedido
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
                  description: Quantidade do item no pedido
                  example: 2
              required:
                - quantity
      responses:
        "200":
          description: Exibe o pedido com o item atualizado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderWithItems"
        "500":
          description: Erro interno do servidor
    delete:
      summary: Remove um item existente do pedido
      tags:
        - Pedidos
      parameters:
        - in: path
          name: id
          required: true
          description: ID do pedido
          schema:
            type: integer
        - in: path
          name: itemId
          required: true
          description: ID do item no pedido
          schema:
            type: integer
      responses:
        "204":
          description: Item removido com sucesso
          content:
            application/json: {}
        "500":
          description: Erro interno do servidor
components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: integer
          description: ID do Pedido
          example: 1
        customerId:
          type: integer
          description: ID do Cliente
          example: 1
        code:
          type: string
          description: Código do Pedido
          example: 9999
        status:
          type: string
          description: Status do Pedido
          example: CREATED

    OrderWithItems:
      allOf:
        - $ref: "#/components/schemas/Order"
      properties:
        items:
          type: array
          description: Itens do Pedido
          items:
            $ref: "#/components/schemas/Item"

    Item:
      type: object
      properties:
        id:
          type: integer
          example: 1
          description: ID do Item
        orderId:
          type: integer
          example: 1
          description: ID do Pedido
        productId:
          type: integer
          example: 1
          description: ID do Produto
        productName:
          type: string
          example: Hamburguer
          description: Nome do Produto
        productDescription:
          type: string
          example: Hamburguer Classico
          description: Descrição do Produto
        unitPrice:
          type: number
          format: float
          example: 12.99
          description: Preço Unitário
        quantity:
          type: integer
          example: 2
          description: Quantidade do Item
        totalPrice:
          type: number
          format: float
          example: 24.98
          description: Preço Total do Item
