paths:
  /orders:
    get:
      summary: Lista todos os pedidos
      tags:
        - Pedidos
      responses:
        "200":
          description: Lista de pedidos
          content:
            application/json:
              schema:
                type: array
                orders: 
                  type: object               
                  properties:
                    id:
                      type: integer
                    code: 
                      type: string
                    status: 
                      type: string
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        category:
                          type: string
                        price:
                          type: number
                          format: float
                        description:
                          type: string
        "500":
          description: Erro interno do servidor
    post:
      summary: Cria um novo pedido
      description: Creates a new order with the specified items.
      tags:
        - Pedidos
      requestBody:
        description: Payload to create a new order
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                orders:
                  type: object
                  properties:
                    items:
                      type: array
                      items:
                        type: object
                        properties:
                          product_id:
                            type: string
                            description: ID of the product
                          quantity:
                            type: integer
                            description: Quantity of the product
                      example:
                        - product_id: "12345"
                          quantity: 2
              required:
                - orders
      responses:
        '200':
          description: Order created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Unique identifier for the order
                  code:
                    type: string
                    description: Order code
                  status:
                    type: string
                    description: Current status of the order
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        product_id:
                          type: string
                        quantity:
                          type: integer
                  customer:
                    type: object
                    properties:
                      name:
                        type: string
                        description: Name of the customer
              example:
                id: "order123"
                code: "ORD456"
                status: "confirmed"
                items:
                  - product_id: "12345"
                    quantity: 2
                customer:
                  name: "John Doe"
        '400':
          description: Invalid input
        '500':
          description: Server error 
  /orders/{id}:
    get: 
      summary: Lista o pedido desejado filtrando pelo ID
      parameters:
        - in: path
          name: cpf
          required: true
          description: CPF do cliente
          schema:
            type: string
      tags:
        - Pedidos
      responses:
        "200":
          description: Lista o pedido desejado filtrando pelo ID
          content:
            application/json:
              schema:
                type: object              
                properties:
                  id:
                    type: integer
                  code: 
                    type: string
                  status: 
                    type: string
                  items:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                      category:
                        type: string
                      price:
                        type: number
                        format: float
                      description:
                        type: string
        "500":
          description: Erro interno do servidor
  /orders/{id}/items:
    post: 
      summary: Cria um novo item no pedido
      tags:
        - Pedidos
      requestBody:
        description: Payload para criar um item no pedido
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                orders:
                  type: object
                  properties:
                    items:
                      type: array
                      items:
                        type: object
                        properties:
                          product_id:
                            type: string
                            description: ID of the product
                          quantity:
                            type: integer
                            description: Quantity of the product
                      example:
                        - product_id: "12345"
                          quantity: 2
              required:
                - orders
  /orders/{id}/items/{itemId}:
    put: 
      summary: Atualiza um item específico do pedido
      tags:
        - Pedidos
      requestBody:
        description: Payload para atualizar um item no pedido
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
                  description: Quantidade do item no pedido
              required:
                - quantity
    delete: 
      summary: Remove um item específico do pedido
      tags:
        - Pedidos
