apiVersion: v1
kind: Service
metadata:
  name: lanchonete-api-service
spec:
  type: NodePort
  selector:
    app: lanchonete-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31200