apiVersion: v1
kind: PersistentVolume
metadata:
  name: lanchonete-db-volume
  labels:
    type: local
    app: lanchonete-db-volume
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql