apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lanchonete-db-volume-claim
  labels:
    app: lanchonete-db
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi