{{- if and .Values.database.useStatefulSet .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
type: Opaque
data:
  {{- .Values.database.secretData | toYaml | nindent 2 }}
{{- end }}